# Generated by Django 3.2.15 on 2022-08-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_time',
            field=models.TimeField(blank=True),
        ),
    ]
