# Generated by Django 3.2.15 on 2022-08-25 23:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20220825_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='number_of_people',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
